/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type FesshMcqMetadata = {
  _type: "fesshMcqMetadata";
  publicationStatus:
    | "draft"
    | "peer_review_pending"
    | "ready_to_publish"
    | "published"
    | "archived";
  firstPublishedDate?: string;
  lastClinicallyReviewed?: string;
  version?: string;
  errataLog?: Array<{
    date: string;
    summary: string;
    resolution: "open" | "corrected" | "no_change" | "duplicate" | "superseded";
    resolutionNotes?: string;
    _type: "erratumEntry";
    _key: string;
  }>;
  originallyAuthored?: string;
  verificationNotes?: string;
  peerReviewed?: boolean;
  peerReviewer?: string;
  peerReviewDate?: string;
};

export type FesshReferenceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "fesshReference";
};

export type FesshStatement = {
  _type: "fesshStatement";
  order: number;
  text: string;
  isTrue: boolean;
  explanation: string;
  primaryReference: FesshReferenceReference;
  secondaryReferences?: Array<
    {
      _key: string;
    } & FesshReferenceReference
  >;
};

export type Callout = {
  _type: "callout";
  type: "info" | "warning" | "pearl";
  title?: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type FesshMcqReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "fesshMcq";
};

export type FesshMockExam = {
  _id: string;
  _type: "fesshMockExam";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  examNumber: number;
  title: string;
  slug: Slug;
  description: string;
  durationMinutes: number;
  passingThreshold?: number;
  questions: Array<
    {
      _key: string;
    } & FesshMcqReference
  >;
  metadata: FesshMcqMetadata;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type FesshMcq = {
  _id: string;
  _type: "fesshMcq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  questionId: string;
  topic: string;
  slug: Slug;
  category:
    | "anatomy"
    | "examination"
    | "imaging"
    | "compressive-neuropathies"
    | "peripheral-nerve-injury"
    | "tendon-injuries"
    | "wrist-trauma"
    | "hand-tumours"
    | "dupuytren-disease"
    | "rheumatoid-hand"
    | "congenital-hand"
    | "microsurgery";
  subCategory?: string;
  difficulty: "basic" | "intermediate" | "advanced";
  stem: string;
  statements: Array<
    {
      _key: string;
    } & FesshStatement
  >;
  metadata: FesshMcqMetadata;
};

export type FesshReference = {
  _id: string;
  _type: "fesshReference";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  referenceType: "journal_article" | "textbook" | "book_chapter" | "guideline";
  authors: Array<string>;
  title: string;
  year: number;
  journal?: string;
  journalAbbreviation?: string;
  volume?: string;
  issue?: string;
  pages?: string;
  edition?: string;
  publisher?: string;
  publisherCity?: string;
  pmid?: string;
  pmcid?: string;
  doi?: string;
  doiNote?: string;
  isbn10?: string;
  isbn13?: string;
  pubmedUrl?: string;
};

export type PodcastEpisode = {
  _id: string;
  _type: "podcastEpisode";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  episodeNumber?: number;
  publishedDate: string;
  duration?: number;
  platform?: "spotify" | "apple" | "youtube" | "other";
  externalUrl: string;
  embedUrl?: string;
  showNotes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  transcript?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  guests?: Array<string>;
  tags?: Array<string>;
};

export type BibReferenceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "bibReference";
};

export type GlossaryTermReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "glossaryTerm";
};

export type Calculator = {
  _id: string;
  _type: "calculator";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  fullName: string;
  slug: Slug;
  locale: "en" | "pl";
  componentName: "quickdash" | "prwe" | "boston-cts" | "mhq" | "mayo-wrist";
  shortDescription: string;
  whenToUse: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          href: string;
          newTab?: boolean;
          _type: "link";
          _key: string;
        }
      | {
          reference: BibReferenceReference;
          _type: "citation";
          _key: string;
        }
      | {
          term: GlossaryTermReference;
          _type: "glossaryTerm";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  pearlsPitfalls?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          href: string;
          newTab?: boolean;
          _type: "link";
          _key: string;
        }
      | {
          reference: BibReferenceReference;
          _type: "citation";
          _key: string;
        }
      | {
          term: GlossaryTermReference;
          _type: "glossaryTerm";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  whyUse: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          href: string;
          newTab?: boolean;
          _type: "link";
          _key: string;
        }
      | {
          reference: BibReferenceReference;
          _type: "citation";
          _key: string;
        }
      | {
          term: GlossaryTermReference;
          _type: "glossaryTerm";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  nextSteps?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          href: string;
          newTab?: boolean;
          _type: "link";
          _key: string;
        }
      | {
          reference: BibReferenceReference;
          _type: "citation";
          _key: string;
        }
      | {
          term: GlossaryTermReference;
          _type: "glossaryTerm";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  evidence: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          href: string;
          newTab?: boolean;
          _type: "link";
          _key: string;
        }
      | {
          reference: BibReferenceReference;
          _type: "citation";
          _key: string;
        }
      | {
          term: GlossaryTermReference;
          _type: "glossaryTerm";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  creatorInsights?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<
      | {
          href: string;
          newTab?: boolean;
          _type: "link";
          _key: string;
        }
      | {
          reference: BibReferenceReference;
          _type: "citation";
          _key: string;
        }
      | {
          term: GlossaryTermReference;
          _type: "glossaryTerm";
          _key: string;
        }
    >;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type ProcedurePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "procedurePage";
};

export type ProcedurePage = {
  _id: string;
  _type: "procedurePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category: "hand-surgery" | "reconstructive-microsurgery" | "skin-cancer";
  language: "en" | "pl";
  audience: "patient" | "peer" | "mixed";
  lastUpdated: string;
  summary: string;
  keyPoints?: {
    question?: string;
    findings?: string;
    meaning?: string;
  };
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
  };
  indications: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Callout)
  >;
  contraindications?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Callout)
  >;
  anatomy: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Callout)
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt: string;
        _type: "image";
        _key: string;
      }
  >;
  positioning?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Callout)
  >;
  approach: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Callout)
  >;
  keySteps: Array<{
    title: string;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt: string;
      _type: "image";
    };
    pitfall?: string;
    _type: "procedureStep";
    _key: string;
  }>;
  closure?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Callout)
  >;
  aftercare: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Callout)
  >;
  complications: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Callout)
  >;
  patientSummary?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  evidence: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Callout)
  >;
  faq?: Array<{
    question: string;
    answer: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "faqItem";
    _key: string;
  }>;
  relatedArticles?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
  relatedProcedures?: Array<
    {
      _key: string;
    } & ProcedurePageReference
  >;
  seoTitle?: string;
  seoDescription?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category: "patient" | "expert" | "fessh-prep" | "news";
  language: "en" | "pl";
  audience: "patient" | "peer" | "mixed";
  author: AuthorReference;
  publishedDate: string;
  lastUpdated?: string;
  excerpt: string;
  standfirst?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  keyPoints?: {
    question?: string;
    findings?: string;
    meaning?: string;
  };
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href: string;
              newTab?: boolean;
              _type: "link";
              _key: string;
            }
          | {
              reference: BibReferenceReference;
              _type: "citation";
              _key: string;
            }
          | {
              term: GlossaryTermReference;
              _type: "glossaryTerm";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        alt: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Callout)
  >;
  relatedArticles?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
  relatedProcedures?: Array<
    {
      _key: string;
    } & ProcedurePageReference
  >;
  seoTitle?: string;
  seoDescription?: string;
};

export type GlossaryTerm = {
  _id: string;
  _type: "glossaryTerm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  term: string;
  termPolish?: string;
  slug: Slug;
  category:
    | "anatomy"
    | "condition"
    | "procedure"
    | "investigation"
    | "treatment"
    | "outcome"
    | "structure"
    | "other";
  shortDefinition: string;
  shortDefinitionPolish?: string;
  fullDefinition?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  fullDefinitionPolish?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  synonyms?: Array<string>;
  relatedTerms?: Array<
    {
      _key: string;
    } & GlossaryTermReference
  >;
  illustration?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt: string;
    _type: "image";
  };
  notesForMateusz?: string;
};

export type BibReference = {
  _id: string;
  _type: "bibReference";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  authors: Array<string>;
  journal: string;
  year: number;
  volume?: string;
  issue?: string;
  pages?: string;
  pmid?: string;
  doi?: string;
  pmcid?: string;
  url?: string;
  pubType:
    | "journal"
    | "book"
    | "chapter"
    | "conference"
    | "online"
    | "guideline";
  editors?: Array<string>;
  publisher?: string;
  publisherLocation?: string;
  edition?: string;
  abstractPreview?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  credentials?: string;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  orcid?: string;
  linkedin?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | FesshMcqMetadata
  | FesshReferenceReference
  | FesshStatement
  | Callout
  | FesshMcqReference
  | FesshMockExam
  | Slug
  | FesshMcq
  | FesshReference
  | PodcastEpisode
  | BibReferenceReference
  | GlossaryTermReference
  | Calculator
  | SanityImageAssetReference
  | ArticleReference
  | ProcedurePageReference
  | ProcedurePage
  | SanityImageCrop
  | SanityImageHotspot
  | AuthorReference
  | Article
  | GlossaryTerm
  | BibReference
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
